### ISSUE TITLE
'statuses/oembed' returns "Error 34: Sorry, that page does not exist"

### ISSUE THREAD

**Issue by jonlambert** [desmondmorris/node-twitter#103]
When making a request to `statuses/oembed` like so:

```js
var id = <tweet-id>
client.get('statuses/oembed', {id: id.toString()}, console.log)
```
It throws:
```
{ message: 'Sorry, that page does not exist', code: 34 }
```

I'm not sure where I'm going wrong here!

**Comment by cliss** [comment]
Were you able to find a solution to this? I'm running into the same issue.

**Comment by 173210** [comment]
I'm having the same issue in my project, but I know the cause. That's because any JavaScript number is double-precision float. So you should handle all ids as strings.
However, Twitter API returns JSONs with ids as numbers. Actually such big numbers are not prohibited in [RFC 4627](https://tools.ietf.org/html/rfc4627) nor in [ECMA-404](http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf).

**Comment by sauravsarkar1234** [comment]
I'm having also the same problem ,even can't solve by making the id to string .How can I solve this?

**Comment by marcoshmendes** [comment]
Facing the same problem at **"favorites/create/:id"**

**Comment by marcoshmendes** [comment]
I solved the problem by not sending parameter ID as query parameter, it must be on body. The docs on Twitter API site is incorrect when show example as query parameter.

OBS. Both in retweet and like endpoints, use ID as string, get the property **id_str** from tweet object

```javascript
client.post('favorites/create', { id: tweetId }, (err, tweet, response) => {});
```

Reference: https://stackoverflow.com/questions/40706111/twitter-api-complaining-that-narrowcast-id-params-must-be-integers
