### ISSUE TITLE
Problem while uploading pics

### ISSUE THREAD

**Issue by Pandazaur** [desmondmorris/node-twitter#114]
Hello,

I wrote the following code:

``` javascript
 /**
         * Upload a media in a tweet
         * message - Message to tweet
         * pathMedia - Path to the media to upload
         */
        uploadMedia(message, pathMedia) {
                var client = this.client;
                var messageTweet = message;
                var pathToMedia = pathMedia;

                return new Promise(function(resolve, reject) {
                        fs.readFile(pathToMedia, function(err, media) {         //_Reading the media to upload
                                if(err) {
                                        reject(err);
                                        return -1;
                                }

                                //_Upload the file, but doesn't post !!
                                client.post('media/upload', {media: media}, function(error, media, response) {
                                        if(error) {
                                                reject(error);
                                                return -2;
                                        }

                                        //_Send the tweet
                                        client.post('statuses/update', {status: messageTweet, media_ids: media.media_id_string}, function(err, tweet, res) {
                                                if(err) {
                                                        reject(err);
                                                        return -1;
                                                }

                                                resolve({media : media,
                                                         message: message});
                                                return 0;
                                        });

                                  });
                        });
                });
        }
```

but sometimes, when the image is posted on Twitter, the image isn't complete, there is a "grey part" just like if the image wasn't fully uploaded before posting on twitter:

![capture du 2015-09-14 22 25 06](https://cloud.githubusercontent.com/assets/10389473/9860956/8b306d2e-5b2f-11e5-993e-4e387503d4e5.png)

**Comment by ORESoftware** [comment]
huh well that's weird isn't it

**Comment by ORESoftware** [comment]
is it

media_ids: media.media_id_string

or 

media_ids: [media.media_id_string]

?

**Comment by Pandazaur** [comment]
With media_ids: media.media_id_string, some pictures are uploaded correctly, but sometimes this problem appears !

**Comment by ORESoftware** [comment]
I actually have a working example if you want it

**Comment by desmondmorris** [comment]
@Pandazaur apologies about the delay.  is this still a problem for you?  I do wonder if it's a problem with the images themselves?  Did you ever find a pattern here?

I am going to close this one for now, mostly because it is pretty old.  We can re-open if @Pandazaur is in a place to continue debugging this.

**Comment by lfvperes** [comment]
This just happened to me. Comparing the pictures that worked fine and the ones that were posted "half grey", I think the reason is the file is too large. Maybe resizing the image will solve it. If anyone tried this and it worked, please let me know!

**Comment by lfvperes** [comment]
I know this issue was closed a long time ago but in case someone needs help like I did, I would like to share what I found.  

The **Image specifications and recommendations** sections in [this guide](https://developer.twitter.com/en/docs/twitter-api/v1/media/upload-media/uploading-media/media-best-practices) from the Twitter API states that image size must be <= 5MB. I checked my files again and the file that was posted as a cropped half grey image was the only file I had that exceeded 5MB. That should be the problem (:
