### ISSUE TITLE
No errors when looking for a username with spaces

### ISSUE THREAD

**Issue by rlavoie** [desmondmorris/node-twitter#166]
When looking for user "@,hghjgjhgkjhlk" results in an error of [ { code: 34, message: 'Sorry, that page does not exist.' } ]. 

When looking for user "@rl test te"  results in an error of null.

It actually returns my feed. 

using this call client.get('statuses/user_timeline', params, function(error, tweets, response)

**Comment by desmondmorris** [comment]
@rlavoie sorry for the delay.  The API itself *should* be responsible for responding with an appropriate error in this case.  This lib does not attempt to validate, or hygiene for that matter, data before it is sent to the API.

Since `user_id` & `screen_name` are optional for this request, I am assuming that Twitter is handling screen names with spaces differently than those with illegal characters.  https://dev.twitter.com/rest/reference/get/statuses/user_timeline

This may be better suited for https://twittercommunity.com/
