### ISSUE TITLE
client.get errors

### ISSUE THREAD

**Issue by Glitttttch** [desmondmorris/node-twitter#192]
I can't seem to get a working output from a get call to Twitter.

Here's my code and resulting errors:

```
var twitter = require('twitter');

var twit = new twitter({
  consumer_key: '...', (removed keys and secrets)
  consumer_secret: '...',
  access_token_key: '...',
  access_token_secret: '...'
});
```

```
twit.get('trends/place', 1, function(error, data, response) {
  if(error) {
    throw error;
  }
  var parseTrend = JSON.parse(data);
  console.log(parseTrend);
});
```

This kills my code and throws an error of : [object Object]

A second get method:

```
twit.get('search/tweets', {q: 'node.js'}, function(error, tweets, response) {
   var parseTrend = JSON.parse(tweets);
   console.log(parseTrend);
   console.log(tweets.length);
});
```

This results in an error:  Status Code: 406 

Am I doing something wrong with my syntax or is there a possible problem with the get method at this time?

It's worth noting that I am also using a client.stream() method, which is working flawlessly.
So I don't think I'm having any issues with keys or oAuth.

Anyone else having issues?

**Comment by brianstone** [comment]
I worked with your code a bit and it appears that using `JSON.parse` could be causing the issues you are experiencing as well as how you are handling errors with `throw error`.

Is there a particular reason that you are using `JSON.parse`?

The `trends/place` route expects an id. Without it (or least without it being formatted correctly), I was getting `code: 34, message: 'Sorry, that page does not exist.'`. Instead of passing the id parameter as you have it, try passing it as follows and let me know if that produces the results you are looking for:
```js
client.get('trends/place', {id: 1}, function(error, data, response) {
  if(error) {
    console.log(error);
  }
```
As for your request with search/tweets, I am currently using this with a simple project I’m working on and was able to get it to pull a list of tweets by doing the following:
```js
client.get('search/tweets', {q: 'node.js'}, function(error, tweets, response) {
    console.log(tweets);
});
```

**Comment by Glitttttch** [comment]
Thanks for the reply Brian.

The `JSON.parse` was definitely the culprit for why my search was giving me an error.
I did finally get the code working and my search ended up looking like this:

```
twit.get('trends/place', {id: 23424977}, function(error, data, response) {
  if(error) {
    console.log(error);
  }
    var jsonResponse = data[0];
    function getNamePair() {
      for (var key in jsonResponse.trends) {
        var name = jsonResponse.trends[key].name;
        var volume = jsonResponse.trends[key].tweet_volume;
        console.log(key, "Name - " + name + ", tweet_vol - " + volume);
      }
    }
    getNamePair();
});
```
This provides me with a log that lists the trend name and tweet volume in the same order that the twitter API distributes it.

**Comment by brianstone** [comment]
Awesome! I'm glad you were able to get it working.

**Comment by desmondmorris** [comment]
Thanks @brianstone 🍺
