### ISSUE TITLE
Can't use retweet twitter API from node.js - error code 34

### ISSUE THREAD

**Issue by z0ph** [desmondmorris/node-twitter#231]
Hello,

I'm trying to figure out of a simple node.js script to retweet using Twitter API. I was able to create favorites, post status, but a simple retweet is not working.

```js
// rt.js
var Twitter = require('twitter');
var config = require('./config.js');
var T = new Twitter(config);

T.post('statuses/retweet/:id', {
  id: '870436914322472960'
}, (err, data, response) => {
  if (err) {
    console.log(err)
  } else {
    console.log(`${data.text} retweet success!`)
  }
})
```

The error message is :

```js
[ { message: 'Sorry, that page does not exist', code: 34 } ]
```

I'm using : twitter@1.7.0 (from npm list)

Thanks for your help.

**Comment by JulienSol** [comment]
Hello,

I was also faced with this error. It occurs because node-twitter don't implement parameters in path.
I release an update with this feature on [my forked repo](https://github.com/JulienSol/node-twitter/tree/update).

In order to use it, you'll have to uninstall node-twitter : 
`npm uninstall twitter`

Then install the github version : 
`npm install git+https://github.com/JulienSol/node-twitter.git#update`

Finally, you'll be able to retweet anything 🙂

**Comment by z0ph** [comment]
@JulienSol 

Strange, my id is passed with the following variable, don't nike to hardcode it.
But whatever, i've tried your code sample, with two different id : 

```js
[ { code: 144, message: 'No status found with that ID.' } ]
```

**Comment by JulienSol** [comment]
Ah ! Yes, you have to convert id to string : 

```JS
T.post('statuses/retweet/' + '870436914322472960', (err, data, response) => {
    if (err) {
        console.log(err)
    } else {
        console.log(`${data.text} retweet success!`)
    }
});
```

**Comment by z0ph** [comment]
@JulienSol It's working, thanks
