### ISSUE TITLE
application only scope

### ISSUE THREAD

**Issue by KyleDavidE** [desmondmorris/node-twitter#81]
Is there a way to use [application-only](https://dev.twitter.com/oauth/application-only) authentication with this library?

**Comment by arno-di-loreto** [comment]
If you're talking about tokens obtained with Fabric sdk, the answer is yes.
Fabric and node-twitter use the same API except that fabric do not handle stream API (But you can access stream with node twitter and your fabric token).
The only "problem" is that you cannot have access to private messages with Fabric (I did not check if it has changed since last January).
Arnaud.

**Comment by KyleDavidE** [comment]
@arno-di-loreto 

I do not think that the Fabric sdk is what I need. What I need is the increased rate limit on searach/statuses which I can get from aplication-only auth. 


Here is the table from the doc for search/statuses:

> | Response formats                     | JSON |
|--------------------------------------|------|
| Requires authentication?             | Yes  |
| Rate limited?                        | Yes  |
| Requests / 15-min window (user auth) | 180  |
| Requests / 15-min window (app auth)  | 450  |


The documentation [here](https://dev.twitter.com/oauth/application-only) specifies how to authenticate as app auth but I don't know how to do that with this library.

**Comment by arno-di-loreto** [comment]
This library do not handle authentication, you use it after getting credentials.
I haven't used this authentication, but you'll probably get the same credentials as with other authentication modes (but no user context) all you have to do is then create the client like this:

var Twitter = require('twitter');
 
var client = new Twitter({
  consumer_key: '',
  consumer_secret: '',
  access_token_key: '',
  access_token_secret: ''
});

But if you need to increase rate limit you should take a look at the stream api as explained here https://dev.twitter.com/rest/public/rate-limiting and here https://dev.twitter.com/streaming/overview

**Comment by passcod** [comment]
Application-only doesn't use the consumer tokens, which is why it's called "application-only", so it requires that _the library_ handle these requests differently. That's why this issue is open.

I'm the author of [mtwitter](https://github.com/passcod/mtwitter), a twitter library that did handle application-only requests. Unfortunately I do not maintain it anymore, but people are still trying to use it... generally I redirect them to this library or to [twit](https://github.com/ttezel/twit), but for application-only requests that doesn't work.

So, advisory: there is demand for this, it does require support in the library itself, and it seems that no updated Node.js twitter library actually supports it. Please consider an implementation, and feel free to rip code out of mine.

**Comment by passcod** [comment]
I commented on issues on the two projects mentioned above: desmondmorris/node-twitter#81 and ttezel/twit#100.

It does look like there is _still_ not any really maintained twitter library in the Node.js ecosystem :( Hopefully someone(s) will step up one day

**Comment by gazzer82** [comment]
I would like to add my voice to this, application only auth is necessary in an node application I'm working on. If someone else has a working version of this with node-twitter I would love it if you could share. Otherwise I guess I'll take a look at trying to do this myself. Or I guess I'll just revert to old school requests . . .

**Comment by gazzer82** [comment]
FYI here is a gist showing the whole flow for application only auth, it includes the token generation which I see no reason can't be part of this framework as we already provide the Key and Secret. https://gist.github.com/Dakuan/5899971

**Comment by gazzer82** [comment]
Just wanted to let people know that this is now implemented as i needed it myself.

**Comment by passcod** [comment]
For reference, the implementation in question was merged in #94.
@KyleDavidE, @desmondmorris: this issue should probably be closed.

**Comment by gibbitz** [comment]
As outlined in the README application-only auth is not working for me. I get `code: 89, message: 'Invalid or expired token.'` when using these credentials. Was the documentation updated after this merge?

**Comment by Tobbe** [comment]
The example is correct, but you need the latest code from github. No release has been made to npm after support for application auth was implemented.

**Comment by desmondmorris** [comment]
@Tobbe I will work on pushing a release this evening.  Thanks for the poke

**Comment by gibbitz** [comment]
ah... Didn't consider they weren't both in sync. Thanks fellas.

**Comment by Tobbe** [comment]
Looks like normal user auth is broken :(

My code works fine with 1.2.5, but does not work with HEAD

**Comment by Tobbe** [comment]
Fixed in PR #98 but that one has not been accepted yet.
